---
name: 11-364 Introduction to Human Aided Deep Learning
theme: jekyll-theme-minimal
description: These notes accompany 11-364, the undergraduate course in Deep Learning @ Carnegie Mellon.
timezone: America/Pittsburgh
