---
name: 11-364 Introduction to Human Aided Deep Learning
title: 11-364 
professor: James K. Baker
theme: jekyll-theme-minimal
description: These notes accompany 11-364, the undergraduate course in Deep Learning @ Carnegie Mellon.
timezone: America/Pittsburgh
collections:
  - presentations
